// <auto-generated />
using System;
using LifeOS.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LifeOS.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260627141012_AddNotificationsAndBudgets")]
    partial class AddNotificationsAndBudgets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("LifeOS.API.Models.Budget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Budgets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 20000m,
                            CreatedAt = new DateTime(2026, 6, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Month = 6,
                            UserId = 1,
                            Year = 2026
                        });
                });

            modelBuilder.Entity("LifeOS.API.Models.CoachFeedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("CoachId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FeedbackText")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CoachFeedbacks");
                });

            modelBuilder.Entity("LifeOS.API.Models.Decision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActualOutcome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Cons")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ExpectedOutcome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsEvaluated")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LessonsLearned")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Pros")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Decisions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActualOutcome = "Compile times reduced by half.",
                            Cons = "Expensive",
                            Description = "Upgrading from 8GB RAM to 32GB RAM",
                            ExpectedOutcome = "Increase productivity by 20%",
                            IsEvaluated = true,
                            LessonsLearned = "Upgrading tools is always a worthy investment.",
                            Pros = "Faster compile times,Better multitasking",
                            Title = "Buy a new laptop",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            ActualOutcome = "Exercised 4 times a week regularly.",
                            Cons = "Monthly membership cost",
                            Description = "Improve physical fitness",
                            ExpectedOutcome = "Be consistent with workouts",
                            IsEvaluated = true,
                            LessonsLearned = "Financial commitment helps maintain consistency.",
                            Pros = "Access to professional equipment,Structured workout environment",
                            Title = "Join gym membership",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            ActualOutcome = "Learned Vite + React hooks and styling.",
                            Cons = "Steep learning curve initially",
                            Description = "Build modern interactive SPA frontends",
                            ExpectedOutcome = "Build premium web dashboards",
                            IsEvaluated = true,
                            LessonsLearned = "Hands-on projects are the best way to learn.",
                            Pros = "Component-based architecture,Rich ecosystem,Better job opportunities",
                            Title = "Start learning React",
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            ActualOutcome = "",
                            Cons = "Market volatility",
                            Description = "Long-term financial savings growth",
                            ExpectedOutcome = "Achieve 8% annualized return",
                            IsEvaluated = false,
                            LessonsLearned = "",
                            Pros = "Low fee,Diversification",
                            Title = "Invest in index funds",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("LifeOS.API.Models.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Expenses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 20000m,
                            Category = "Job",
                            Date = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Monthly Budget",
                            Type = "Income",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 3927m,
                            Category = "Food",
                            Date = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Groceries & Dining out",
                            Type = "Expense",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Amount = 2887.50m,
                            Category = "Bills",
                            Date = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Electricity & Water Bills",
                            Type = "Expense",
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            Amount = 1963.50m,
                            Category = "Entertainment",
                            Date = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Movie & Concert Tickets",
                            Type = "Expense",
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            Amount = 1732.50m,
                            Category = "Travel",
                            Date = new DateTime(2026, 6, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cab & Metro fare",
                            Type = "Expense",
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            Amount = 1039.50m,
                            Category = "Miscellaneous",
                            Date = new DateTime(2026, 6, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Miscellaneous purchases",
                            Type = "Expense",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("LifeOS.API.Models.Habit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MaxStreak")
                        .HasColumnType("int");

                    b.Property<int>("Streak")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Habits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MaxStreak = 10,
                            Streak = 5,
                            Title = "Exercise",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            MaxStreak = 5,
                            Streak = 3,
                            Title = "Reading",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            MaxStreak = 0,
                            Streak = 0,
                            Title = "Meditation",
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            MaxStreak = 0,
                            Streak = 0,
                            Title = "Water Intake",
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            MaxStreak = 0,
                            Streak = 0,
                            Title = "No Sugar",
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            MaxStreak = 0,
                            Streak = 0,
                            Title = "Wake Up Early",
                            UserId = 1
                        },
                        new
                        {
                            Id = 7,
                            MaxStreak = 0,
                            Streak = 0,
                            Title = "Journaling",
                            UserId = 1
                        },
                        new
                        {
                            Id = 8,
                            MaxStreak = 0,
                            Streak = 0,
                            Title = "Skin Care",
                            UserId = 1
                        },
                        new
                        {
                            Id = 9,
                            MaxStreak = 0,
                            Streak = 0,
                            Title = "Study",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("LifeOS.API.Models.HabitLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CompletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("HabitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("HabitLogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompletedDate = new DateTime(2026, 6, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            HabitId = 1
                        },
                        new
                        {
                            Id = 2,
                            CompletedDate = new DateTime(2026, 6, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            HabitId = 2
                        });
                });

            modelBuilder.Entity("LifeOS.API.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("LifeOS.API.Models.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("ReminderSent")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Deadline = new DateTime(2026, 6, 26, 21, 35, 20, 0, DateTimeKind.Utc),
                            Description = "Work",
                            IsCompleted = false,
                            Priority = "High",
                            ReminderSent = false,
                            Title = "Project Presentation",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Deadline = new DateTime(2026, 6, 26, 23, 24, 54, 0, DateTimeKind.Utc),
                            Description = "Personal",
                            IsCompleted = false,
                            Priority = "Medium",
                            ReminderSent = false,
                            Title = "Gym Membership Renewal",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Deadline = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Atomic habits review",
                            IsCompleted = false,
                            Priority = "Low",
                            ReminderSent = false,
                            Title = "Read 10 pages of book",
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            CompletedAt = new DateTime(2026, 6, 22, 19, 0, 0, 0, DateTimeKind.Utc),
                            Deadline = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "EF Core setup",
                            IsCompleted = true,
                            Priority = "Medium",
                            ReminderSent = false,
                            Title = "Refactor database migrations",
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            CompletedAt = new DateTime(2026, 6, 23, 18, 0, 0, 0, DateTimeKind.Utc),
                            Deadline = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Vite react setup",
                            IsCompleted = true,
                            Priority = "High",
                            ReminderSent = false,
                            Title = "Setup Vite Frontend configuration",
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            CompletedAt = new DateTime(2026, 6, 24, 2, 0, 0, 0, DateTimeKind.Utc),
                            Deadline = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "JWT logic",
                            IsCompleted = true,
                            Priority = "High",
                            ReminderSent = false,
                            Title = "Implement user authentication",
                            UserId = 1
                        },
                        new
                        {
                            Id = 7,
                            CompletedAt = new DateTime(2026, 6, 24, 23, 50, 0, 0, DateTimeKind.Utc),
                            Deadline = new DateTime(2026, 6, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Figma draft",
                            IsCompleted = true,
                            Priority = "Medium",
                            ReminderSent = false,
                            Title = "Design dashboard cards wireframe",
                            UserId = 1
                        },
                        new
                        {
                            Id = 8,
                            CompletedAt = new DateTime(2026, 6, 24, 12, 0, 0, 0, DateTimeKind.Utc),
                            Deadline = new DateTime(2026, 6, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "CORS check",
                            IsCompleted = true,
                            Priority = "Low",
                            ReminderSent = false,
                            Title = "Verify API CORS policies",
                            UserId = 1
                        },
                        new
                        {
                            Id = 9,
                            CompletedAt = new DateTime(2026, 6, 24, 16, 0, 0, 0, DateTimeKind.Utc),
                            Deadline = new DateTime(2026, 6, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "xUnit tests",
                            IsCompleted = true,
                            Priority = "Low",
                            ReminderSent = false,
                            Title = "Write initial unit tests",
                            UserId = 1
                        },
                        new
                        {
                            Id = 10,
                            CompletedAt = new DateTime(2026, 6, 25, 1, 0, 0, 0, DateTimeKind.Utc),
                            Deadline = new DateTime(2026, 6, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Serilog setup",
                            IsCompleted = true,
                            Priority = "Medium",
                            ReminderSent = false,
                            Title = "Configure logging middlewares",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("LifeOS.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedCoachId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Qualification")
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedCoachId = 2,
                            CreatedAt = new DateTime(2026, 6, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "john@lifeos.com",
                            IsApproved = true,
                            PasswordHash = "user123",
                            Role = "User",
                            Username = "john_user"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "bob@lifeos.com",
                            IsApproved = true,
                            PasswordHash = "coach123",
                            Qualification = "Certified Nutritionist & Personal Trainer",
                            Role = "Coach",
                            Username = "coach_bob"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 5, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@lifeos.com",
                            IsApproved = true,
                            PasswordHash = "admin123",
                            Role = "Admin",
                            Username = "admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
