// <auto-generated />
using System;
using LifeOS.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LifeOS.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("LifeOS.API.Models.Budget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Budgets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 20000m,
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Month = 6,
                            UserId = 1,
                            Year = 2026
                        },
                        new
                        {
                            Id = 2,
                            Amount = 25000m,
                            CreatedAt = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Month = 5,
                            UserId = 1,
                            Year = 2026
                        });
                });

            modelBuilder.Entity("LifeOS.API.Models.CoachFeedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("CoachId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FeedbackText")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CoachFeedbacks");
                });

            modelBuilder.Entity("LifeOS.API.Models.Decision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActualOutcome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Cons")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ExpectedOutcome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsEvaluated")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LessonsLearned")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Pros")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Decisions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActualOutcome = "Energy and mood improved significantly. I could focus better and got more done in less time.",
                            Category = "Health",
                            Cons = "Less output at work",
                            Description = "I was working long hours and neglecting my health. Started feeling tired, unmotivated and mentally drained.",
                            ExpectedOutcome = "I will have more energy, improve my focus and maintain long-term productivity.",
                            IsEvaluated = true,
                            LessonsLearned = "Health is the foundation of everything. Prioritizing it early leads to better results in all areas of life.",
                            Pros = "More energy, better sleep",
                            Title = "Prioritize health over overtime work",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            ActualOutcome = "Glad I didn't buy it, money remained saved.",
                            Category = "Personal",
                            Cons = "Missed out on fun gadget",
                            Description = "Tempted to buy a new tablet but didn't actually need it.",
                            ExpectedOutcome = "More savings, no clutter",
                            IsEvaluated = true,
                            LessonsLearned = "Waiting helped me save money and avoid regret.",
                            Pros = "Saved money",
                            Title = "Avoid impulse purchases on gadgets",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            ActualOutcome = "Acquired 90% syllabus coverage.",
                            Category = "Relationship",
                            Cons = "FOMO",
                            Description = "Needed to study for CDAC exam, invited to a party.",
                            ExpectedOutcome = "Complete study goals",
                            IsEvaluated = true,
                            LessonsLearned = "Protecting my time helped me focus on priorities.",
                            Pros = "Better grades",
                            Title = "Say no to social event for study",
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            ActualOutcome = "Felt organized and relaxed.",
                            Category = "Lifestyle",
                            Cons = "Less sleep at night",
                            Description = "Waking up late made me rush through the day.",
                            ExpectedOutcome = "Productive and calm mornings",
                            IsEvaluated = true,
                            LessonsLearned = "Mornings set the tone for a productive day.",
                            Pros = "Relaxed morning",
                            Title = "Start a morning routine",
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            ActualOutcome = "Not evaluated yet.",
                            Category = "Finance",
                            Cons = "Market volatility",
                            Description = "Deciding where to invest excess monthly savings.",
                            ExpectedOutcome = "Consistent 8% annual return",
                            IsEvaluated = false,
                            LessonsLearned = "Long-term thinking beats short-term gains.",
                            Pros = "Compounding growth",
                            Title = "Invest in long-term Index Fund",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("LifeOS.API.Models.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Expenses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 20000m,
                            Category = "Job",
                            Date = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Monthly Budget Allocation",
                            Type = "Income",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 3927m,
                            Category = "Food",
                            Date = new DateTime(2026, 6, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Groceries & Dinner",
                            Type = "Expense",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Amount = 2887.50m,
                            Category = "Bills",
                            Date = new DateTime(2026, 6, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Electricity & Internet Bills",
                            Type = "Expense",
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            Amount = 1963.50m,
                            Category = "Entertainment",
                            Date = new DateTime(2026, 6, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Movie tickets & Popcorn",
                            Type = "Expense",
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            Amount = 1732.50m,
                            Category = "Travel",
                            Date = new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Uber & Train ticket",
                            Type = "Expense",
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            Amount = 1039.50m,
                            Category = "Miscellaneous",
                            Date = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Miscellaneous purchases",
                            Type = "Expense",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("LifeOS.API.Models.Habit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MaxStreak")
                        .HasColumnType("int");

                    b.Property<int>("Streak")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Habits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MaxStreak = 10,
                            Streak = 5,
                            Title = "Exercise",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            MaxStreak = 7,
                            Streak = 5,
                            Title = "Reading",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            MaxStreak = 0,
                            Streak = 0,
                            Title = "Meditation",
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            MaxStreak = 0,
                            Streak = 0,
                            Title = "Water Intake",
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            MaxStreak = 0,
                            Streak = 0,
                            Title = "No Sugar",
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            MaxStreak = 0,
                            Streak = 0,
                            Title = "Wake Up Early",
                            UserId = 1
                        },
                        new
                        {
                            Id = 7,
                            MaxStreak = 0,
                            Streak = 0,
                            Title = "Journaling",
                            UserId = 1
                        },
                        new
                        {
                            Id = 8,
                            MaxStreak = 0,
                            Streak = 0,
                            Title = "Skin Care",
                            UserId = 1
                        },
                        new
                        {
                            Id = 9,
                            MaxStreak = 0,
                            Streak = 0,
                            Title = "Study",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("LifeOS.API.Models.HabitLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CompletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("HabitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("HabitLogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompletedDate = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HabitId = 1
                        },
                        new
                        {
                            Id = 2,
                            CompletedDate = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            HabitId = 1
                        },
                        new
                        {
                            Id = 3,
                            CompletedDate = new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            HabitId = 1
                        },
                        new
                        {
                            Id = 4,
                            CompletedDate = new DateTime(2026, 6, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            HabitId = 1
                        },
                        new
                        {
                            Id = 5,
                            CompletedDate = new DateTime(2026, 6, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            HabitId = 1
                        },
                        new
                        {
                            Id = 6,
                            CompletedDate = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HabitId = 2
                        },
                        new
                        {
                            Id = 7,
                            CompletedDate = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            HabitId = 2
                        },
                        new
                        {
                            Id = 8,
                            CompletedDate = new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            HabitId = 2
                        },
                        new
                        {
                            Id = 9,
                            CompletedDate = new DateTime(2026, 6, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            HabitId = 2
                        },
                        new
                        {
                            Id = 10,
                            CompletedDate = new DateTime(2026, 6, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            HabitId = 2
                        });
                });

            modelBuilder.Entity("LifeOS.API.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("LifeOS.API.Models.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("ReminderSent")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Other",
                            Deadline = new DateTime(2026, 7, 1, 22, 20, 0, 0, DateTimeKind.Utc),
                            Description = "Work",
                            IsCompleted = false,
                            Priority = "High",
                            ReminderSent = false,
                            Title = "Project Presentation",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Category = "Other",
                            Deadline = new DateTime(2026, 7, 2, 2, 10, 0, 0, DateTimeKind.Utc),
                            Description = "Personal",
                            IsCompleted = false,
                            Priority = "Medium",
                            ReminderSent = false,
                            Title = "Gym Membership Renewal",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Category = "Other",
                            Deadline = new DateTime(2026, 7, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Atomic habits review",
                            IsCompleted = false,
                            Priority = "Low",
                            ReminderSent = false,
                            Title = "Read 10 pages of book",
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            Category = "Other",
                            CompletedAt = new DateTime(2026, 6, 26, 2, 0, 0, 0, DateTimeKind.Utc),
                            Deadline = new DateTime(2026, 6, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "EF Core setup",
                            IsCompleted = true,
                            Priority = "Medium",
                            ReminderSent = false,
                            Title = "Refactor database migrations",
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            Category = "Other",
                            CompletedAt = new DateTime(2026, 6, 27, 4, 0, 0, 0, DateTimeKind.Utc),
                            Deadline = new DateTime(2026, 6, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Vite react setup",
                            IsCompleted = true,
                            Priority = "High",
                            ReminderSent = false,
                            Title = "Setup Vite Frontend configuration",
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            Category = "Other",
                            CompletedAt = new DateTime(2026, 6, 28, 1, 0, 0, 0, DateTimeKind.Utc),
                            Deadline = new DateTime(2026, 6, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "JWT logic",
                            IsCompleted = true,
                            Priority = "High",
                            ReminderSent = false,
                            Title = "Implement user authentication",
                            UserId = 1
                        },
                        new
                        {
                            Id = 7,
                            Category = "Other",
                            CompletedAt = new DateTime(2026, 6, 28, 23, 0, 0, 0, DateTimeKind.Utc),
                            Deadline = new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Figma draft",
                            IsCompleted = true,
                            Priority = "Medium",
                            ReminderSent = false,
                            Title = "Design dashboard cards wireframe",
                            UserId = 1
                        },
                        new
                        {
                            Id = 8,
                            Category = "Other",
                            CompletedAt = new DateTime(2026, 6, 29, 22, 0, 0, 0, DateTimeKind.Utc),
                            Deadline = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "CORS check",
                            IsCompleted = true,
                            Priority = "Low",
                            ReminderSent = false,
                            Title = "Verify API CORS policies",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("LifeOS.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedCoachId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Qualification")
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SecurityAnswerHash")
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedCoachId = 2,
                            CreatedAt = new DateTime(2026, 6, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "john@lifeos.com",
                            IsApproved = true,
                            PasswordHash = "user123",
                            Role = "User",
                            Username = "john"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "bob@lifeos.com",
                            IsApproved = true,
                            PasswordHash = "coach123",
                            Qualification = "Certified Nutritionist & Personal Trainer",
                            Role = "Coach",
                            Username = "coach_bob"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 5, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@lifeos.com",
                            IsApproved = true,
                            PasswordHash = "admin123",
                            Role = "Admin",
                            Username = "admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
